### ISSUE TITLE
run error debian 

### ISSUE THREAD

**Issue by piotrek2555** [dgalli1/ytm-mpd#3]
root@debian:~# docker run ghcr.io/dgalli1/ytm-mpd:main
Creating new renderer: undefined
node:net:1214
    throw new ERR_MISSING_ARGS(['options', 'port', 'path']);
          ^

TypeError [ERR_MISSING_ARGS]: The "options" or "port" or "path" argument must be specified
    at Socket.connect (node:net:1214:11)
    at Object.connect (node:net:236:17)
    at MPDClient.connect (/app/node_modules/mpd2/lib/index.js:57:34)
    at Object.connect (/app/node_modules/mpd-api/lib/index.js:7:28)
    at file:///app/dist/player/MpdPlayer.js:18:40
    at new MpdPlayer (file:///app/dist/player/MpdPlayer.js:24:11)
    at file:///app/dist/index.js:11:16
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7) {
  code: 'ERR_MISSING_ARGS'
}

Node.js v20.10.0

When i try  BARE METAL install:

root@debian:~/ytm-mpd# npm run build

> ytm-mpd@0.0.2 build
> tsc

sh: 1: tsc: not found

**Comment by dgalli1** [comment]
It's running on node v18
tsc should be provided via the "typescript" dependency, did you run npm install before executing npm run build? (Edit: nvm i forgot this in the install instructions, its added now)

`const config = {
    host: process.env.MPD_HOST,
    port: process.env.MPD_PORT,
    password: process.env.MPD_PASSWORD
};`

You have to define the env variables before running the docker container. (Look at the docker compose or use  the -e flag for docker run
