### ISSUE TITLE
playing error

### ISSUE THREAD

**Issue by galgofa** [dgalli1/ytm-mpd#5]
After connecting some video plaid but then after return with following error in the container log:

`[yt-cast-receiver] Player.next()
[yt-cast-receiver] No next video in queue.
[yt-cast-receiver] Play autoplay video: E0loeRBI4MU.
[yt-cast-receiver] Player.stop()
/app/node_modules/mpd2/lib/index.js:147
        : this._reject(new MPDError(desc))
                       ^
MPDError: Not playing
    at MPDClient._receive (/app/node_modules/mpd2/lib/index.js:147:24)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'PLAYER_SYNC',
`

**Comment by dgalli1** [comment]
For some reason it lost the connection to the mpd player.

Do you have any log messages above that one which would indicate something like this?

**Comment by galgofa** [comment]
^
TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at Session._Session_refreshLoungeToken (file:///app/node_modules/yt-cast-receiver/dist/mjs/lib/app/Session.js:365:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v20.10.0
Creating new renderer: 192.168.72.88
Connected to renderer!
[yt-cast-receiver] Failed to get value for key 'mdxContext.cl' in data store: (Error) [node-persist][readFile] .node-persist/storage/201320bf36690e3af5cbd087efb44323 does not look like a valid storage file! Error: [node-persist][readFile] .node-persist/storage/201320bf36690e3af5cbd087efb44323 does not look like a valid storage file!
    at /app/node_modules/node-persist/src/local-storage.js:316:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
[yt-cast-receiver] DIAL server listening on port 3000
[yt-cast-receiver] Connecting sender through DIAL...
[yt-cast-receiver] (YouTube) Sender connected: XIAOMI Mi 10 (user: Mr)
Connected to XIAOMI Mi 10
[yt-cast-receiver] DefaultPlaylistRequestHandler failed to mark video 9pPP3vpUx10 as watched: (TypeError) fetch failed TypeError: fetch failed
    at HTTPClient.fetch (/app/node_modules/undici/index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[yt-cast-receiver] Player.play(): 9pPP3vpUx10 @ 0s
Play 9pPP3vpUx10 at position 0s
[yt-cast-receiver] Player.resume()
[yt-cast-receiver] Player.play(): 9pPP3vpUx10 @ 0s
Play 9pPP3vpUx10 at position 0s
Media URL: https://rr1---sn-4vguioxu-5uiz.googlevideo.com/videoplayback?expire=1704237501&ei=XUWUZeunG6fSi9oPnpqwkAs&ip=77.49.224.19&id=o-ABT50Cjs3hqRgCtCU9qQeox2bEB1zIGVtVbW2uVxDdFD&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=K8&mm=31%2C29&mn=sn-4vguioxu-5uiz%2Csn-nv47zn7r&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=903750&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=21603019&dur=1334.799&lmt=1704203027504243&mt=1704215585&fvip=1&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgAfBXJAgAO84wKUwhASythGov5zCQ0NMa4c9EP7rjrfYCIEosgiNBNArpd7rbjlKOHwJiyao_7UKVg9PzQ4m7ZBh8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgVhqbRhhl23wgHJJ93Q1Z_yW2cen5s52O6ZztD4v3nYcCIFdz3oM01EDbSMdLAKTBQzDJhOvVjoYkqyXasObGHLeQ
Media URL: https://rr1---sn-4vguioxu-5uiz.googlevideo.com/videoplayback?expire=1704237502&ei=XkWUZaCgIMzM6dsP_5e0sA4&ip=77.49.224.19&id=o-AATTqo_qkBpUuIJCENTYBHRFlIsEWHCJCoqqdC2BAJVV&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=K8&mm=31%2C29&mn=sn-4vguioxu-5uiz%2Csn-nv47zn7r&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=21&initcwndbps=903750&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=21603019&dur=1334.799&lmt=1704203027504243&mt=1704215585&fvip=1&keepalive=yes&fexp=24007246&c=IOS&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgS9adu3LHZsXDR0UKPOY82YZDa0kQk7-ntWRaJoLgmrkCIQDhdYASol23dl3tXUz54PpVf04X29HKxqlkqD7wG6Oy5Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRgIhAKQSW__KzeLMSCHboUrEIbnjVZdn97lXZy1kl1BTbpyVAiEA-BZA5IR7jFEsA8cSyfH570cIuAl4qL4vNCKuYzK37Xg%3D
Status changed to stop from PLAY

